bitbag_sylius_upselling_plugin_shop_partial_related_products_index:
    path: /products/{slug}/related
    methods: [GET]
    defaults:
        _controller: sylius.controller.product:indexAction
        _sylius:
            template: $template
            repository:
                method: findLatestByChannel
                arguments:
                    - "expr:service('sylius.context.channel').getChannel()"
                    - "expr:service('sylius.context.locale').getLocaleCode()"
                    - '!!int $count'
