bitbag_sylius_crossselling_plugin_shop:
    resource: "@BitBagSyliusCrossSellingPlugin/Resources/config/routing/shop_routing.yaml"
    prefix: /{_locale}
    requirements:
        _locale: ^[a-z]{2}(?:_[A-Z]{2})?$
