twig_hooks:
  hooks:
    'sylius_shop.product.show.page.product_listing':
      related_products:
        template: "@BitBagSyliusCrossSellingPlugin/Shop/Product/_relatedProducts.html.twig"
        priority: 15
      associations:
        template: "@SyliusShop/product/show/page/product_listing/associations.html.twig"
        priority: 10
