sylius_ui:
    events:
        sylius.shop.product.show.content:
            blocks:
                related_products:
                    template: "@BitBagSyliusCrossSellingPlugin/Shop/Product/_relatedProducts.html.twig"
                    priority: 15
