parameters:
    bitbag_crossselling.elasticsearch.related_products.index: related_products

fos_elastica:
    indexes:
        bitbag_related_products:
            index_name: '%bitbag_crossselling.elasticsearch.related_products.index%_%kernel.environment%'
            properties:
                state: ~
            persistence:
                driver: orm
                model: '%sylius.model.order.class%'
                listener:
                    defer: true
                    logger: true
                elastica_to_model_transformer:
                    ignore_missing: true
